### ISSUE TITLE
PWA 404 Error

### ISSUE THREAD

**Issue by C0deNuclear** [yuorb/enthrirhc#13]
Greetings, the PWA format for enţrirç seems to be broken currently. See image below:
![image](https://github.com/yuorb/enthrirhc/assets/141107922/eb3fa67e-456c-4e8a-b9dd-077a706f4581)

OS: iOS 17.2.1
Browser: Safari

**Comment by lomirus** [comment]
Hi, @C0deNuclear. I recently changed the repository name from `enthrirhs` to `enthrirhc` but forgot to update the base URL. Today I have updated it and released a new minor version. Can you try it and see if it's resolved now?
